syntax = "proto3";

package resonance.logic.v1;

import "common/v1/event.proto";
import "common/v1/message.proto";

option go_package = "github.com/ceyewan/resonance/api/gen/go/logic/v1;logicv1";

service ChatService {
  rpc SendEvent(SendEventRequest) returns (SendEventResponse);
}

message SendEventRequest {
  string session_id = 1;

  oneof payload {
    resonance.common.v1.Message message = 10;
    resonance.common.v1.MessageRecall recall = 11;
    resonance.common.v1.MessageEdit edit = 12;
  }
}

message SendEventResponse {
  int64 event_id = 1;
  int64 seq_id = 2;
  int64 timestamp_ms = 3;
}
